version: "3.8"

services:
  ranger-usersync:
    build: .
    container_name: ranger-usersync
    environment:
      - LDAP_URL=ldaps://144.24.127.112:636
      - TS_FILE=/opt/java/openjdk/lib/security/cacerts
      - TS_PASS=changeit
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    extra_hosts:
      - "144.24.127.112:host-gateway"
    networks:
      - apache-solr_default
      - ldap_network
    # environment:
    #   - HADOOP_CREDSTORE_PASSWORD=changeit
    # volumes:
    #   - ./ranger-usersync/conf:/opt/ranger-usersync/conf
    #   - ./ranger-usersync/install.properties:/opt/ranger-usersync/install.properties
networks:
  apache-solr_default:
    external: true

  ldap_network:
    external: true